dist: bionic
language: node_js

addons:
  apt:
    packages:
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libxslt1.1
      - libvpx5
    # This is required to run chromium
      - libgbm1
    # this is needed for running headful tests
      - xvfb

notifications:
  email: false

cache:
  directories:
    - node_modules

node_js:
  - stable

script:
  - npm test
